//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaneiStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Date { get; set; }
        public int PlotId { get; set; }
        public decimal Transportation { get; set; }
        public decimal TheCostOfRepair { get; set; }
        public Nullable<decimal> FortyPercent { get; set; }
        public Nullable<decimal> SixtyPercent { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Dsc { get; set; }
    }
}
