//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaneiStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaneiStoreEntities2 : DbContext
    {
        public SaneiStoreEntities2()
            : base("name=SaneiStoreEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Store> Store { get; set; }
    }
}
