//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaneiStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int PlotId { get; set; }
        public string PlotName { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
        public int Provider { get; set; }
        public string PurchaseDate { get; set; }
        public string Dsc { get; set; }
    }
}
